service: quals-scoreboard
provider:
  memorySize: 128
  name: aws
  profile: ooo
  runtime: python3.6
  vpc:
    securityGroupIds:
      - sg-04848976f5c2510dd
    subnetIds:
      - subnet-0d13ea8e8a578a8d7
  stage: dev
  region: us-east-2
functions:
  hello:
    handler: handler.hello
